name: Release Toolbox to PyPi

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # No cache for releases (the default for tag pushes), to prevent cache poisoning
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v10.1.0
        with:
          python-version: "3.12"
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
