name: Test

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    uses: prepare-assignment/actions-ci/.github/workflows/test.yml@main
    with:
      mypy-argument: "prepare_toolbox"